/**
 * Proof run (not a vitest spec): boot the REAL assembled IDEalize app (the
 * whole `idealize` profile) headlessly in both themes and walk one agent's
 * chip through its task's life, reading every surface that names the agent's
 * state.
 *
 * What it proves, in order, per theme:
 *
 * 1. A real chat is launched and answers one turn, so comm lists it and the
 *    roster serves its chip.
 * 2. A Studio assignment to that chat plus `working` reads **Working** on the
 *    roster route: the task state reaches the chip.
 * 3. `done` reads **Finished** on the roster route, with the finished task's
 *    goal on the task line. The collapsed sidebar's rail shows the chip
 *    captioned Finished with the tick badge and no presence dot, and its
 *    accessible name says the chat is safe to close; the tick's ink against
 *    its fill is measured off the computed styles.
 * 4. The floating bar's page (`?dsh-desktop-mode=askbar`) shows the same chip
 *    the same way, and its panel's head reads "Finished, safe to close".
 * 5. The Studio view's agents row for that chat reads "Finished, safe to
 *    close" where it read "Idle".
 * 6. A new assignment to the same chat takes the chip out of Finished on the
 *    route and in the rail: the state ends when the agent is given new work.
 *
 * The model behind the one real turn is `@deepseek-ai/dsh-llm-mock-server`, so
 * the run needs no provider key; a generated `--patch` points the default model
 * at the DeepSeek route the mock answers on (the shipped default is OpenRouter).
 *
 * Isolation: the run refuses to start unless `DSH_HOME` and `HOME` both point
 * inside the temporary directory it made.
 *
 * Usage: OUT=.idealize/proof pnpm exec tsx packages/idealize/askbar/proof/finished-proof.mts
 */
import { spawn } from 'node:child_process'
import type { ChildProcess } from 'node:child_process'
import { mkdir, mkdtemp, realpath, rm, writeFile } from 'node:fs/promises'
import { createServer } from 'node:net'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
// Resolved from apps/web's devDependency: the proof borrows the web e2e browser.
import { chromium } from '../../../../apps/web/node_modules/playwright/index.mjs'
import type { Browser, Page } from '../../../../apps/web/node_modules/playwright/index.mjs'
import { startMockLlmServer } from '../../../test-support/llm-mock-server/src/index.ts'
import { assertSettled, openApp } from '../../../../.idealize/proof-settle.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(here, '..', '..', '..', '..')
const out = process.env.OUT ?? '.idealize/proof'
await mkdir(out, { recursive: true })

// ── Isolation, verified before anything is written ─────────────────────────
const root = await mkdtemp(join(tmpdir(), 'idealize-finished-proof-'))
const home = join(root, 'home')
const dshHome = join(root, 'dsh-home')
let projectDir = join(root, 'project')
for (const dir of [home, dshHome, projectDir]) await mkdir(dir, { recursive: true })
// macOS tmp rides a symlink; the workspace store canonicalises its path and
// the Studio timeline must be keyed by the same spelling.
projectDir = await realpath(projectDir)
await writeFile(join(projectDir, 'NOTES.md'), '# Notes\n\nThe finished-chip proof reads this file.\n')

const env = {
  ...process.env,
  HOME: home,
  DSH_HOME: dshHome,
  XDG_CONFIG_HOME: join(home, '.config'),
  XDG_DATA_HOME: join(home, '.local', 'share'),
  IDEALIZE_SKIP_TOUR: '1',
}
if (!env.DSH_HOME.startsWith(root) || !env.HOME.startsWith(root)) {
  throw new Error('refusing to run: DSH_HOME and HOME must both be inside the scratch root')
}
console.log(`isolated: HOME=${env.HOME}`)
console.log(`isolated: DSH_HOME=${env.DSH_HOME}`)

/** A port the OS has just confirmed is free. */
async function freePort(): Promise<number> {
  return await new Promise((resolve, reject) => {
    const server = createServer()
    server.once('error', reject)
    server.listen(0, '127.0.0.1', () => {
      const address = server.address()
      const port = typeof address === 'object' && address !== null ? address.port : 0
      server.close(() => { resolve(port) })
    })
  })
}

const mock = await startMockLlmServer({
  host: '127.0.0.1',
  port: 0,
  apiKey: 'mock-key',
  sequence: ['tool_call_success', 'success'],
  repeatLast: true,
  toolName: 'read',
  toolArguments: JSON.stringify({ file_path: join(projectDir, 'NOTES.md') }),
})

// The shipped default model runs through OpenRouter, which the scripted model
// does not serve; this run points the default back at the DeepSeek route the
// mock answers on.
const patchPath = join(root, 'finished-proof.patch.yml')
await writeFile(patchPath, [
  '# Generated by packages/idealize/askbar/proof/finished-proof.mts.',
  '- id: agent-default-model',
  '  config:',
  '    provider: deepseek-official',
  '    model: deepseek-v4-flash',
  '',
].join('\n'))

const hostEnv = { ...env, DEEPSEEK_API_KEY: 'mock-key', DEEPSEEK_BASE_URL: `${mock.baseURL}/v1` }

/** Boot `dsh --profile idealize` and wait for the Studio route and the RPC channel to answer. */
async function boot(port: number): Promise<ChildProcess> {
  const child = spawn(
    'node',
    ['--import', 'tsx/esm', 'apps/cli/src/bin.ts', '--profile', 'idealize', '--patch', patchPath, '--host', '127.0.0.1', '--port', String(port)],
    { cwd: repoRoot, env: hostEnv, stdio: ['ignore', 'pipe', 'pipe'] },
  )
  child.stderr?.on('data', (chunk: Buffer) => { process.stderr.write(`  host! ${chunk.toString()}`) })
  let exited = false
  child.once('exit', () => { exited = true })
  const deadline = Date.now() + 180_000
  for (;;) {
    if (exited) throw new Error('the host exited before it listened; an unbuilt frontend is the usual cause (pnpm run build)')
    if (Date.now() > deadline) {
      child.kill('SIGKILL')
      throw new Error('the host never started listening')
    }
    try {
      const response = await fetch(`http://127.0.0.1:${String(port)}/idealize/studio/state?project=${encodeURIComponent(projectDir)}`)
      if (response.ok && Array.isArray((await response.json() as { tasks?: unknown[] }).tasks)) {
        const probe = await fetch(`http://127.0.0.1:${String(port)}/api/workspace.list`, {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ type: 'client-request', rpcId: crypto.randomUUID(), method: 'workspace.list', payload: {} }),
        })
        if (probe.ok) return child
      }
    } catch {
      // Not listening yet; the loop is the wait.
    }
    await new Promise(resolve => setTimeout(resolve, 500))
  }
}

/** Stop a booted host and wait for it to exit. */
async function stop(child: ChildProcess): Promise<void> {
  child.kill('SIGTERM')
  await new Promise<void>((resolve) => {
    const timer = setTimeout(() => { child.kill('SIGKILL'); resolve() }, 10_000)
    child.once('exit', () => { clearTimeout(timer); resolve() })
  })
}

const port = await freePort()
const host = await boot(port)
const base = `http://127.0.0.1:${String(port)}`
console.log(`app: ${base}`)

/** One JSON-RPC call over the app's own HTTP surface. */
async function rpc<T>(method: string, payload: unknown): Promise<T> {
  const response = await fetch(new URL(`/api/${method}`, base), {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ type: 'client-request', rpcId: crypto.randomUUID(), method, payload }),
  })
  if (!response.ok) throw new Error(`${method} failed: ${String(response.status)} ${await response.text()}`)
  return await response.json() as T
}

await rpc('workspace.create', { path: projectDir })
const projectName = projectDir.split('/').pop() ?? projectDir

const browser: Browser = await chromium.launch()

/** Release the browser, the host and the scripted model whatever the outcome. */
async function teardown(): Promise<void> {
  await browser.close().catch(() => undefined)
  await stop(host).catch(() => undefined)
  await mock.close().catch(() => undefined)
}
process.on('uncaughtException', (error) => {
  console.error(error)
  void teardown().then(() => { process.exit(1) })
})
process.on('unhandledRejection', (reason) => {
  console.error(reason)
  void teardown().then(() => { process.exit(1) })
})

const failures: string[] = []
/** Record a failed expectation without abandoning the remaining screenshots. */
function expect(ok: boolean, what: string): void {
  console.log(`  ${ok ? 'PASS' : 'FAIL'}  ${what}`)
  if (!ok) failures.push(what)
}

const AUTH = { 'x-idealize-auth': '1', 'content-type': 'application/json' }

/** Record one Studio event through the Studio's own route. */
async function record(event: Record<string, unknown>): Promise<void> {
  const response = await fetch(`${base}/idealize/studio/event`, {
    method: 'POST', headers: AUTH, body: JSON.stringify({ project: projectDir, ...event }),
  })
  if (!response.ok) throw new Error(`recording ${JSON.stringify(event)} failed: ${String(response.status)} ${await response.text()}`)
}

interface RosterChip { id: string; name: string; state: string; task: string | null }

/** One chat's chip, off the roster route. */
async function chipOf(session: string): Promise<RosterChip | undefined> {
  const response = await fetch(`${base}/idealize/askbar/roster?project=${encodeURIComponent(projectDir)}`)
  const chips = (await response.json() as { chips: RosterChip[] }).chips
  return chips.find(chip => chip.id === session)
}

/** Open the project and launch a Chat brain through the welcome card. */
async function launchChat(page: Page): Promise<void> {
  // The second theme boots onto the first theme's chat: start a fresh one.
  if (await page.locator('[data-launcher-step]').count() === 0) {
    await page.getByRole('button', { name: 'New chat' }).first().click()
    const fresh = await page.locator('[data-launcher-step]').waitFor({ timeout: 10_000 }).then(() => true, () => false)
    if (!fresh) {
      await page.getByText(projectName, { exact: true }).first().click({ timeout: 30_000 })
      await page.locator('[data-launcher-step]').waitFor({ timeout: 30_000 })
    }
  }
  if (await page.locator('[data-brain]').count() === 0) {
    for (let attempt = 0; attempt < 5; attempt++) {
      await page.locator('[data-launcher-step="space"] [data-space="chat"]').click()
      const advanced = await page.locator('[data-launcher-step="brain"]').waitFor({ timeout: 5_000 })
        .then(() => true, () => false)
      if (advanced) break
      if (attempt === 4) throw new Error('the Chat tile never advanced to the brain step')
    }
  }
  await page.locator('[data-brain]').first().click()
  await page.waitForTimeout(2_000)
}

/** Send one prompt through the shipped composer and wait for the turn to settle. */
async function turn(page: Page, text: string): Promise<void> {
  const composer = page.locator('[data-composer-seat] textarea, textarea').first()
  await composer.waitFor({ timeout: 30_000 }).catch(async (error: unknown) => {
    await page.screenshot({ path: join(out, 'debug-finished-composer.png') })
    throw error
  })
  await composer.click()
  await composer.fill(text)
  await page.keyboard.press('Meta+Enter')
  await page.waitForFunction(
    () => document.querySelectorAll('[data-running], [data-turn-running]').length === 0,
    undefined,
    { timeout: 90_000 },
  ).catch(() => undefined)
  await page.waitForTimeout(2_500)
}

/** What one chip renders, read off the DOM with the computed paint of its tick. */
async function chipOnPage(page: Page, session: string): Promise<{
  state: string | null
  label: string | null
  caption: string | null
  tick: boolean
  presenceDot: boolean
  badgeFill: string | null
  badgeInk: string | null
} | null> {
  return page.evaluate(({ id }) => {
    const chip = document.querySelector(`[data-chip-id="${id}"]`)
    if (chip === null) return null
    const wrap = chip.firstElementChild
    const tick = wrap?.querySelector('svg')?.parentElement ?? null
    const paint = tick === null ? null : getComputedStyle(tick)
    return {
      state: chip.getAttribute('data-chip-state'),
      label: chip.getAttribute('aria-label'),
      caption: chip.lastElementChild?.textContent ?? null,
      tick: tick !== null,
      // The avatar, then at most one badge or dot, then unread: a dot is an empty span.
      presenceDot: [...(wrap?.children ?? [])].slice(1).some(node => node.childNodes.length === 0),
      badgeFill: paint?.backgroundColor ?? null,
      badgeInk: paint?.color ?? null,
    }
  }, { id: session })
}

/** WCAG contrast ratio of two computed `rgb()` colours. */
function contrast(first: string, second: string): number {
  const luminance = (colour: string): number => {
    const channels = (colour.match(/[\d.]+/g) ?? []).slice(0, 3).map(Number).map((value) => {
      const unit = value / 255
      return unit <= 0.03928 ? unit / 12.92 : ((unit + 0.055) / 1.055) ** 2.4
    })
    return 0.2126 * (channels[0] ?? 0) + 0.7152 * (channels[1] ?? 0) + 0.0722 * (channels[2] ?? 0)
  }
  const [lighter, darker] = [luminance(first), luminance(second)].sort((left, right) => right - left)
  return ((lighter ?? 0) + 0.05) / ((darker ?? 0) + 0.05)
}

/** Wait until the chip on the page carries the state, then settle and capture. */
async function awaitChipState(page: Page, session: string, state: string): Promise<boolean> {
  return page.waitForFunction(
    ({ id, want }) => document.querySelector(`[data-chip-id="${id}"]`)?.getAttribute('data-chip-state') === want,
    { id: session, want: state },
    { timeout: 20_000 },
  ).then(() => true, () => false)
}

/** Chats an earlier theme already walked. */
const walked = new Set<string>()

for (const theme of ['light', 'dark'] as const) {
  console.log(`\n── ${theme} ────────────────────────────────────────────────`)
  const context = await browser.newContext({
    viewport: { width: 1280, height: 840 },
    deviceScaleFactor: 2,
    locale: 'en-GB',
    colorScheme: theme,
  })
  const page = await context.newPage()
  const pageErrors: string[] = []
  page.on('pageerror', error => pageErrors.push(String(error)))

  // 1. A real chat, so comm lists it and the roster serves its chip.
  await openApp(page, base, { ready: page.getByRole('button', { name: 'Brains', exact: true }) })
  await launchChat(page)
  await turn(page, `Read NOTES.md and tell me what it says (${theme}).`)
  // The roster lists the project's agent chats and never the Studio chat, so
  // the one chip no earlier theme walked is the chat just launched.
  const rosterRead = await fetch(`${base}/idealize/askbar/roster?project=${encodeURIComponent(projectDir)}`)
  const session = (await rosterRead.json() as { chips: RosterChip[] }).chips.find(chip => !walked.has(chip.id))?.id
  if (session === undefined) throw new Error('the roster names no chat this theme launched')
  walked.add(session)
  const before = await chipOf(session)
  expect(before !== undefined && before.state !== 'finished', `the chat has a chip before any task, not finished (got ${JSON.stringify(before)})`)

  // 2. The task state reaches the chip.
  const taskId = `t-close-${theme}`
  await record({ kind: 'assignment', subtype: 'new-task', author: 'user', target: session, taskId, body: `Tidy the notes (${theme})` })
  await record({ kind: 'task-update', subtype: 'working', author: session, taskId })
  const working = await chipOf(session)
  expect(working?.state === 'working' && working.task === `Tidy the notes (${theme})`, `a working task reads Working with its goal (got ${JSON.stringify(working)})`)

  // 3. Done reads Finished, on the route and in the collapsed sidebar's rail.
  await record({ kind: 'task-update', subtype: 'done', author: session, taskId, target: 'user' })
  const finished = await chipOf(session)
  expect(finished?.state === 'finished', `a done task reads Finished on the roster route (got ${JSON.stringify(finished)})`)
  expect(finished?.task === `Tidy the notes (${theme})`, 'the finished chip keeps the finished task\'s goal on its task line')

  await page.getByRole('button', { name: 'Collapse sidebar' }).first().click()
  await page.locator('[data-askbar-rail][data-home="sidebar"]').waitFor({ timeout: 20_000 })
  expect(await awaitChipState(page, session, 'finished'), 'the collapsed sidebar\'s rail shows the chip finished')
  await assertSettled(page, `finished-sidebar-${theme}`)
  await page.screenshot({ path: join(out, `finished-sidebar-${theme}.png`) })
  const railChip = await chipOnPage(page, session)
  console.log(`  sidebar rail chip: ${JSON.stringify(railChip)}`)
  expect(railChip?.caption === 'Finished', `the chip is captioned Finished (got ${JSON.stringify(railChip?.caption)})`)
  expect(railChip?.label?.endsWith('Finished, safe to close') === true, `its accessible name says it is safe to close (got ${JSON.stringify(railChip?.label)})`)
  expect(railChip?.tick === true && railChip.presenceDot === false, 'it wears the tick badge and no presence dot')
  const ratio = railChip?.badgeFill == null || railChip.badgeInk == null ? 0 : contrast(railChip.badgeFill, railChip.badgeInk)
  console.log(`  tick ink ${String(railChip?.badgeInk)} on fill ${String(railChip?.badgeFill)}: ${ratio.toFixed(2)}:1`)
  expect(ratio >= 3, `the tick reads against its fill at 3:1 or better, the WCAG floor for a graphic (got ${ratio.toFixed(2)}:1)`)
  const chipBox = await page.locator(`[data-chip-id="${session}"]`).boundingBox()
  if (chipBox !== null) {
    await page.screenshot({
      path: join(out, `finished-sidebar-chip-${theme}.png`),
      clip: { x: Math.max(0, chipBox.x - 12), y: Math.max(0, chipBox.y - 12), width: chipBox.width + 24, height: chipBox.height + 24 },
    })
  }

  // 4. The floating bar's page shows the same chip, and its panel says safe to close.
  // The main page holds the origin's long-lived connections, so a second page
  // stalls on load; the one page visits the bar and comes back.
  const bar = page
  await bar.setViewportSize({ width: 520, height: 840 })
  await bar.goto(`${base}/?dsh-desktop-mode=askbar`, { waitUntil: 'load' })
  await bar.locator('[data-askbar-bar]').waitFor({ timeout: 60_000 })
  expect(await awaitChipState(bar, session, 'finished'), 'the floating bar shows the chip finished')
  const barChip = await chipOnPage(bar, session)
  expect(barChip?.caption === 'Finished' && barChip.tick, `the floating bar captions and badges it the same way (got ${JSON.stringify(barChip)})`)
  await bar.locator(`[data-chip-id="${session}"]`).focus()
  await bar.keyboard.press('Enter')
  const panel = bar.getByRole('dialog')
  const panelShown = await panel.waitFor({ timeout: 10_000 }).then(() => true, () => false)
  const panelText = panelShown ? await panel.textContent() : null
  expect(panelText?.includes('Finished, safe to close') === true, `the panel's head says Finished, safe to close (got ${JSON.stringify(panelText?.slice(0, 120))})`)
  await bar.waitForTimeout(400)
  await bar.screenshot({ path: join(out, `finished-bar-${theme}.png`) })
  await page.setViewportSize({ width: 1280, height: 840 })
  await openApp(page, base, { ready: page.getByRole('button', { name: 'Brains', exact: true }) })

  // 5. The Studio view's agents row says the same.
  if (await page.locator('[data-studio-card]').count() === 0) await page.getByRole('button', { name: 'Open sidebar' }).first().click()
  await page.locator('[data-studio-card]').click()
  await page.locator(`[data-studio-task="${taskId}"]`).waitFor({ timeout: 30_000 })
  const agentRow = page.locator(`[data-studio-agent="${session}"]`)
  await agentRow.scrollIntoViewIfNeeded()
  const agentText = await agentRow.textContent()
  expect(agentText?.includes('Finished, safe to close') === true, `the Studio's agents row reads Finished, safe to close (got ${JSON.stringify(agentText)})`)
  await assertSettled(page, `finished-studio-${theme}`)
  await page.screenshot({ path: join(out, `finished-studio-${theme}.png`) })

  // 6. New work ends the finished state.
  await record({ kind: 'assignment', subtype: 'new-task', author: 'user', target: session, taskId: `t-next-${theme}`, body: `Draft the summary (${theme})` })
  const reassigned = await chipOf(session)
  expect(reassigned !== undefined && reassigned.state !== 'finished' && reassigned.task === `Draft the summary (${theme})`,
    `a new assignment takes the chip out of Finished and names the new task (got ${JSON.stringify(reassigned)})`)
  await page.getByRole('button', { name: 'Collapse sidebar' }).first().click()
  await page.locator('[data-askbar-rail][data-home="sidebar"]').waitFor({ timeout: 20_000 })
  expect(await awaitChipState(page, session, reassigned?.state ?? 'ready'), `the rail's chip follows to ${String(reassigned?.state)}`)
  const after = await chipOnPage(page, session)
  expect(after?.tick === false && after.presenceDot, `the tick is gone and the presence dot is back (got ${JSON.stringify(after)})`)
  await assertSettled(page, `finished-reassigned-${theme}`)
  await page.screenshot({ path: join(out, `finished-reassigned-${theme}.png`) })
  // Close that task out so the next theme's chat starts from a settled project.
  await record({ kind: 'task-update', subtype: 'cancelled', author: 'user', taskId: `t-next-${theme}` })
  await page.getByRole('button', { name: 'Open sidebar' }).first().click()

  if (pageErrors.length > 0) {
    console.error(`  page errors: ${JSON.stringify(pageErrors)}`)
    failures.push(`page errors in ${theme}`)
  }
  await context.close()
}

await teardown()
await rm(root, { recursive: true, force: true })

if (failures.length > 0) {
  console.error(`\n${String(failures.length)} expectation(s) failed:`)
  for (const failure of failures) console.error(`  - ${failure}`)
  process.exit(1)
}
console.log(`\nwrote finished-chip proofs to ${out}`)
