/**
 * Regenerate `src/policy/ruleset.ts` from a checkout of the canonical
 * documentation repository (jamiejefferson/ajjent-vault). Usage:
 *
 *     pnpm exec tsx packages/idealize/doc-policy/scripts/generate-policy.ts <checkout>
 *
 * The generator is the mechanical half of a re-pin: it stamps the checkout's
 * HEAD sha and commit date into `RULESET_VERSION`, embeds the source texts
 * verbatim, and extracts the structural constants from them. Interpretation
 * (which extractions exist, what optionality means) lives here as reviewed
 * source; every extraction fails loud when the canonical repository drifts
 * from the fields this generator understands, so a re-pin that changes the
 * ruleset's structure forces a reviewed generator change too.
 */

import { execFileSync } from 'node:child_process'
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const checkout = process.argv[2]
if (checkout === undefined) {
  console.error('usage: generate-policy.ts <ajjent-vault checkout>')
  process.exit(1)
}

const git = (...args: string[]): string =>
  execFileSync('git', ['-C', checkout, ...args], { encoding: 'utf8' }).trim()

const sha = git('rev-parse', 'HEAD')
const date = git('log', '-1', '--format=%ad', '--date=short')

const conventions = readFileSync(join(checkout, 'CONVENTIONS.md'), 'utf8')
const template = readFileSync(join(checkout, 'templates', 'project-index.md'), 'utf8')

/** Fail the generation with a drift diagnostic. */
function drift(what: string): never {
  throw new Error(`canonical repository drifted: ${what} — review the generator against ${sha}`)
}

// Canonical directories: top-level directories of the checkout, excluding
// repository plumbing (dot-directories, scripts/). Sorted for stability.
const dirs = readdirSync(checkout)
  .filter(entry => !entry.startsWith('.') && entry !== 'scripts')
  .filter(entry => statSync(join(checkout, entry)).isDirectory())
  .sort()
if (!dirs.includes('Projects') || !dirs.includes('templates')) drift('Projects/ or templates/ missing')

// Canonical root files: non-hidden root files, excluding repository plumbing.
const rootFiles = readdirSync(checkout)
  .filter(entry => !entry.startsWith('.'))
  .filter(entry => statSync(join(checkout, entry)).isFile())
  .sort()
if (!rootFiles.includes('CONVENTIONS.md')) drift('CONVENTIONS.md missing from the root file set')

// Status vocabulary: the inline comment on the template/CONVENTIONS `status:`
// example line (`status: active  # active | draft | ...`).
const statusMatch = /^status:.*#\s*([a-z| ]+)$/m.exec(conventions)
if (statusMatch?.[1] === undefined) drift('status vocabulary comment not found in CONVENTIONS.md')
const statuses = statusMatch[1].split('|').map(status => status.trim()).filter(Boolean)
if (statuses.length < 2) drift('status vocabulary parsed to fewer than two values')

// Project-index frontmatter fields, from the template's own frontmatter.
// A field whose template value is empty or `[]` is optional (repo, live,
// tags); a field carrying a placeholder is required.
const templateFrontmatter = /^---\n([\s\S]*?)\n---/.exec(template)?.[1]
if (templateFrontmatter === undefined) drift('project-index template has no frontmatter')
const required: string[] = []
const optional: string[] = []
for (const line of templateFrontmatter.split('\n')) {
  const field = /^([a-z_]+):\s*(.*)$/.exec(line)
  if (field?.[1] === undefined) continue
  const value = (field[2] ?? '').trim()
  ;(value === '' || value === '[]' ? optional : required).push(field[1])
}
if (!required.includes('status') || !required.includes('last_touched')) {
  drift('template frontmatter lost status/last_touched')
}

// Stale-active threshold: "no update in N days" in CONVENTIONS.md (the
// phrase may wrap across a source line break).
const staleMatch = /no update\s+in (\d+)\s*days/.exec(conventions)
if (staleMatch?.[1] === undefined) drift('stale-active threshold not found in CONVENTIONS.md')
const staleDays = Number(staleMatch[1])

// Decision entry heading: pin the documented `### YYYY-MM-DD — Title` form,
// verified against the CONVENTIONS example.
if (!/^### \d{4}-\d{2}-\d{2} — .+$/m.test(conventions)) {
  drift('decision heading example not found in CONVENTIONS.md')
}

/** Escape text for embedding in a template literal. */
const embed = (text: string): string =>
  text.replaceAll('\\', '\\\\').replaceAll('`', '\\`').replaceAll('$', '\\$')

const list = (values: readonly string[]): string =>
  values.map(value => `'${value}'`).join(', ')

const module_ = `/**
 * GENERATED by scripts/generate-policy.ts from jamiejefferson/ajjent-vault
 * at commit ${sha} (${date}).
 * Do not edit by hand — re-pin by rerunning the generator against a new
 * checkout and reviewing the diff (procedure in the package README).
 * @module @idealize/doc-policy/src/policy/ruleset
 */

/** Identity of the pinned canonical ruleset. */
export interface RulesetVersion {
  /** Pinned commit sha of the canonical repository. */
  sha: string
  /** Commit date of the pin (YYYY-MM-DD). */
  date: string
  /** Human-readable version recorded with every scan (DOC-07). */
  id: string
}

/** The pinned canonical ruleset version. */
export const RULESET_VERSION: RulesetVersion = {
  sha: '${sha}',
  date: '${date}',
  id: 'ajjent-vault@${sha.slice(0, 7)} (${date})',
}

/** Directories every canonical vault carries. */
export const CANONICAL_DIRS = [${list(dirs)}] as const

/** Root files the canonical structure recognizes (others raise a finding). */
export const CANONICAL_ROOT_FILES = [${list(rootFiles)}] as const

/** Frontmatter fields a project \`_index.md\` must carry. */
export const PROJECT_INDEX_REQUIRED_FIELDS = [${list(required)}] as const

/** Frontmatter fields a project \`_index.md\` may carry empty. */
export const PROJECT_INDEX_OPTIONAL_FIELDS = [${list(optional)}] as const

/** The closed \`status\` vocabulary. */
export const STATUS_VOCABULARY = [${list(statuses)}] as const

/** Absolute ISO dates only — the vault convention for every date field. */
export const ISO_DATE_RE = /^\\d{4}-\\d{2}-\\d{2}$/

/** Cross-project decision file names: \`Decisions/YYYY-MM-DD-*.md\`. */
export const DECISION_FILE_RE = /^\\d{4}-\\d{2}-\\d{2}-.+\\.md$/

/** Appended decision entry headings: \`### YYYY-MM-DD — Title\`. */
export const DECISION_HEADING_RE = /^### \\d{4}-\\d{2}-\\d{2} — .+$/m

/** Days without update after which an \`active\` project is challenged. */
export const STALE_ACTIVE_DAYS = ${staleDays}

/** CONVENTIONS.md of the pinned canonical repository, verbatim. */
export const CONVENTIONS_SOURCE = \`${embed(conventions)}\`

/** templates/project-index.md of the pinned canonical repository, verbatim. */
export const PROJECT_INDEX_TEMPLATE = \`${embed(template)}\`
`

const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'policy', 'ruleset.ts')
writeFileSync(out, module_)
console.log(`wrote ${out} from ${sha} (${date})`)
