/**
 * GENERATED by scripts/generate-policy.ts from jamiejefferson/ajjent-vault
 * at commit 9f7cfe992a0fc20a36425fd502a22873cbcf4e3c (2026-08-12).
 * Do not edit by hand — re-pin by rerunning the generator against a new
 * checkout and reviewing the diff (procedure in the package README).
 * @module @idealize/doc-policy/src/policy/ruleset
 */

/** Identity of the pinned canonical ruleset. */
export interface RulesetVersion {
  /** Pinned commit sha of the canonical repository. */
  sha: string
  /** Commit date of the pin (YYYY-MM-DD). */
  date: string
  /** Human-readable version recorded with every scan (DOC-07). */
  id: string
}

/** The pinned canonical ruleset version. */
export const RULESET_VERSION: RulesetVersion = {
  sha: '9f7cfe992a0fc20a36425fd502a22873cbcf4e3c',
  date: '2026-08-12',
  id: 'ajjent-vault@9f7cfe9 (2026-08-12)',
}

/** Directories every canonical vault carries. */
export const CANONICAL_DIRS = ['Decisions', 'People', 'Projects', 'Reference', 'templates'] as const

/** Root files the canonical structure recognizes (others raise a finding). */
export const CANONICAL_ROOT_FILES = ['AGENTS.md', 'CLAUDE.md', 'CONVENTIONS.md', 'LICENSE', 'README.md'] as const

/** Frontmatter fields a project `_index.md` must carry. */
export const PROJECT_INDEX_REQUIRED_FIELDS = ['project', 'status', 'type', 'created', 'last_touched'] as const

/** Frontmatter fields a project `_index.md` may carry empty. */
export const PROJECT_INDEX_OPTIONAL_FIELDS = ['repo', 'live', 'tags'] as const

/** The closed `status` vocabulary. */
export const STATUS_VOCABULARY = ['active', 'draft', 'parked', 'blocked', 'done', 'archived'] as const

/** Absolute ISO dates only — the vault convention for every date field. */
export const ISO_DATE_RE = /^\d{4}-\d{2}-\d{2}$/

/** Cross-project decision file names: `Decisions/YYYY-MM-DD-*.md`. */
export const DECISION_FILE_RE = /^\d{4}-\d{2}-\d{2}-.+\.md$/

/** Appended decision entry headings: `### YYYY-MM-DD — Title`. */
export const DECISION_HEADING_RE = /^### \d{4}-\d{2}-\d{2} — .+$/m

/** Days without update after which an `active` project is challenged. */
export const STALE_ACTIVE_DAYS = 30

/** CONVENTIONS.md of the pinned canonical repository, verbatim. */
export const CONVENTIONS_SOURCE = `# Conventions

The operating manual. \`CLAUDE.md\` is the short version that stays in context;
this is the reference.

## Structure

\`\`\`
Projects/<Name>/_index.md    The project's map. One per project, always present.
Projects/<Name>/*.md         Supporting notes, linked from the index.
Decisions/YYYY-MM-DD-*.md    Cross-project decisions.
Reference/                   Durable material not scoped to one project.
People/<name>.md             Who they are, what they care about, how to reach them.
\`\`\`

A project folder without an \`_index.md\` is invisible to every script here. The
index is the contract.

## Frontmatter

Every note carries YAML frontmatter. Scripts read it, so the field names are
fixed. Adding fields is fine; renaming these is not, without updating \`scripts/\`.

### Project index

\`\`\`yaml
---
project: short-name          # canonical short name, stable over the project's life
status: active               # active | draft | parked | blocked | done | archived
type: index
repo: ~/code/short-name      # absolute or ~ path to the repository, if there is one
live: https://example.com    # deployed URL, if there is one
created: 2026-01-15
last_touched: 2026-01-15     # ISO date; the session-close hook maintains this
tags: []
---
\`\`\`

\`repo:\` is the single most important field. It is what lets the agent verify a
claim instead of believing it, and it is what the session-close hook matches on.
Without it a project is unverifiable, which is the normal state for client work
that produces no code — and worth knowing about explicitly.

### Everything else

\`\`\`yaml
---
project: short-name          # which project this belongs to, if any
type: note                   # note | decision | reference | person | meeting
created: 2026-01-15
tags: []
---
\`\`\`

## Status, and why it must be allowed to be wrong

\`status\` is only useful if it can be false. A vault where everything says \`active\`
carries no information at all.

\`/vault-review\` therefore challenges it: any project marked \`active\` with no update
in 30 days gets raised for confirmation or reclassification. Answering "yes, still
active" is a real answer and takes two seconds. Never silently reclassify a project
on the user's behalf.

## Decisions

Decisions are append-only, inside the project index under \`## Decisions\` for
project-scoped ones, or in \`Decisions/\` when they span projects.

\`\`\`markdown
### 2026-03-04 — Use db:push rather than migrations
Chose to skip the migration layer while the schema is still moving weekly.
Accepted cost: no rollback path, so production changes need a manual backup first.
Revisit when the schema settles or a second developer joins.
\`\`\`

To reverse a decision, add a new entry. Say what changed, and name the entry it
supersedes by date. Do not edit the original — the fact that you believed
something on a given date, and why, is the part worth keeping.

## Traps

A trap is anything that will cost someone an hour because it is not discoverable
from the code. They go under \`## Traps\` in the project index, and they earn their
place by being non-obvious.

\`\`\`markdown
## Traps
- ⚠️ \`2.0.0\` in the changelog looks newer than \`0.1.x\`, but its source was never
  committed. The \`archive/v2-*\` branches are the 0.1.x line, not the lost source.
- Deploys only work from the canonical repo; the copy under \`website/\` is stale.
\`\`\`

Good traps are specific and falsifiable. "Be careful with the build" is not a trap.

## Links

\`[[Wikilinks]]\` by note title. They are plain text, so they cost nothing and work
in any tool. Link liberally, including to notes that don't exist yet — an unresolved
link marks something worth writing rather than an error.

## Dates

ISO 8601 (\`2026-01-15\`), always absolute. A note saying "fixed last Tuesday" is
useless six months later and actively misleading to an agent trying to date events.

## What not to write down

- Anything reconstructible from git. Point at the repo instead.
- Anything a company's own system is authoritative for. Reference it by name.
- Secrets, tokens, keys. Record where the credential lives, never its value.
- Meeting transcripts in full. Record what was decided and what changed.
`

/** templates/project-index.md of the pinned canonical repository, verbatim. */
export const PROJECT_INDEX_TEMPLATE = `---
project: SHORT-NAME
status: active
type: index
repo:
live:
created: YYYY-MM-DD
last_touched: YYYY-MM-DD
tags: []
---

# Project name

One or two lines: what this is, and who it's for.

## State

Where the project is now, in a short paragraph. What is live, what is in flight,
what is blocked and on whom. Update when the situation genuinely shifts, not every
session — the session log below already records the small movements.

## Open threads

- Thread, with enough context that it still makes sense after a fortnight away
- Another one

## Next actions

- A concrete thing to do next
- Another concrete thing

## Decisions

Append-only, newest last. Never edit an entry; supersede it with a new one.

### YYYY-MM-DD — Decision in a short sentence
Why this over the alternatives. What it costs. What would make you revisit it.

## Traps

Things that will cost someone an hour because the code doesn't reveal them.

- ⚠️ Specific, falsifiable trap

## Session log

Maintained automatically by \`scripts/session-close.py\`. Commits land here with
their short hashes; nothing else should be written in this section by hand.
`
