/**
 * The owl clips' URLs, shared by both faces: the host serves each clip at its
 * file name under {@link OWL_CLIP_PREFIX} and the browser half points the
 * wizard's `<video>` at it. Each file name carries a hash of the clip's
 * bytes, so a changed clip gets a new URL and the immutable cache never serves
 * a stale one. Pure data, so the client program compiles it without the host
 * face's imports.
 * GENERATED by scripts/gen-owl-clips.ts from sources outside the repo — do
 * not edit by hand; regenerate with:
 *
 *   pnpm tsx scripts/gen-owl-clips.ts "<OnboardingOwls/transparent dir>"
 * @module @idealize/onboarding/owl-clip-urls
 */
import type { OnboardingStepId } from './step-ids.ts'

/** The route prefix the host serves the clips under. */
export const OWL_CLIP_PREFIX = '/idealize/onboarding/owl'

/** Each clip's served file name: `<clip id>.<content hash>.webm`. */
export const OWL_CLIP_FILES = {
  'agents': 'agents.229eacc5c801.webm',
  'tools': 'tools.00486e67af58.webm',
  'projects-folder': 'projects-folder.4ef0abb5e535.webm',
  'documentation-folder': 'documentation-folder.3690947292f5.webm',
  'finish': 'finish.b0276f3af7b4.webm',
} as const

/** A clip drawn for the wizard, one per source file. */
export type OwlClipId = keyof typeof OWL_CLIP_FILES

/** The clip each wizard step plays. */
const STEP_CLIPS: Record<OnboardingStepId, OwlClipId> = {
  'agents': 'agents',
  'tools': 'tools',
  'projects-folder': 'projects-folder',
  'documentation-folder': 'documentation-folder',
  'finish': 'finish',
  'skills-folder': 'documentation-folder',
}

/**
 * The clip URL for one wizard step.
 * @param step - the wizard step.
 * @returns the same-origin URL the host serves that step's clip at.
 */
export function owlClipUrl(step: OnboardingStepId): string {
  return `${OWL_CLIP_PREFIX}/${OWL_CLIP_FILES[STEP_CLIPS[step]]}`
}
