/**
 * The twelve agent-name pools (496 unique names). A project draws its chat
 * names from one pool, so names never repeat inside a project and two
 * projects on different pools never clash. Source: JJ's project-name-pools.md.
 */

/** Twelve pools of 41 or 42 names each. */
export const NAME_POOLS: readonly (readonly string[])[] = [
  [
    'Qui-Gon Jinn', 'Sabé', 'TC-14', 'Obi-Wan Kenobi',
    'Finis Valorum', 'Maoi Madakor', 'Padmé Amidala', 'Nute Gunray',
    'Antidar Williams', 'Anakin Skywalker', 'Ki-Adi-Mundi', 'Saché',
    'Jar Jar Binks', 'Lott Dod', 'Wald', 'Palpatine',
    'Rune Haako', 'Weazel', 'Darth Maul', 'Boss Nass',
    'Adi Gallia', 'Shmi Skywalker', 'Watto', 'Aldar Beedo',
    'Mace Windu', 'Sebulba', 'Amee', 'Yoda',
    'Fodesinbeed Annodue', 'Ark Roose', 'Sio Bibble', 'Plo Koon',
    'Ben Quadinaros', 'Quarsh Panaka', 'Daultay Dofine', 'Boles Roor',
    'C-3PO', 'Ric Olié', 'Clegg Holdfast', 'R2-D2',
    'Bib Fortuna', 'Depa Billaba',
  ],
  [
    'Dineé Ellberger', 'Melee', 'Yaddle', 'Dud Bolt',
    'Neva Kee', 'Yané', 'Ebe E. Endocott', 'Ody Mandrell',
    'Yarael Poof', 'Eeth Koth', 'OOM-9', 'Count Dooku',
    'Eirtaé', 'Oppo Rancisis', 'Jango Fett', 'Elan Mak',
    'Porro Dolphe', 'Boba Fett', 'Even Piell', 'Rabé',
    'Zam Wesell', 'Gasgano', 'Ratts Tyerell', 'Bail Organa',
    'Gavyn Sykes', 'Roos Tarpals', 'Cliegg Lars', 'Jabba the Hutt',
    'Saesee Tiin', 'Owen Lars', 'Jira', 'Seek',
    'Beru Whitesun', 'Kitster Banai', 'Teemto Pagalies', 'Dexter Jettster',
    'Mars Guo', 'Tey How', 'Typho', 'Mawhonic',
    'Wan Sandage', 'Dormé',
  ],
  [
    'Jamillia', 'Elan Sleazebaggano', 'WA-7', 'Lama Su',
    'Cordé', 'Agen Kolar', 'Taun We', 'Versé',
    'Achk Med-Beq', 'Jocasta Nu', 'Teckla Minnau', 'Ame Llom',
    'Poggle the Lesser', 'Kit Fisto', 'Ayy Vida', 'Wat Tambor',
    'Luminara Unduli', 'Bairdon Jace', 'Passel Argente', 'Shaak Ti',
    'COO-2180', 'San Hill', 'Aayla Secura', 'Denaria Kee',
    'Shu Mai', 'Barriss Offee', 'Ganwick Trag', 'Sun Fac',
    'Bultar Swan', 'Ister Paddie', 'Mas Amedda', 'Coleman Trebor',
    'Joclad Danva', 'Ask Aak', 'Pablo-Jill', 'Jynne Celwik',
    'Orn Free Taa', 'Sar Labooda', 'Kell Borean', 'Sly Moore',
    'Hermione Bagwa', 'Khaat Qiyn',
  ],
  [
    'Lexi Dio', 'Rotta', 'Gree', 'Lumas Etima',
    'Wullf Yularen', 'Neyo', 'Lunae Minx', '4A-7',
    'Bacara', 'Nicanas Tassu', 'Fox', 'Cin Drallig',
    'R4-P17', 'KRONOS-327', 'Bana Breemu', 'Roth-Del Masona',
    'TC-70', 'Bene', 'Sephjet Josall', 'Grievous',
    'Boga', 'Zett Jukassa', 'Chewbacca', 'Calek Kelbin',
    'Ahsoka Tano', 'Wilhuff Tarkin', 'Cellheim Anujo', 'Asajj Ventress',
    'Tion Medon', 'Chi Eekway', 'Rex', 'Apailana',
    'Elle', 'Cody', 'Tarfful', 'Fang Zar',
    'Ziro the Hutt', 'Baron Papanoida', 'GH-7', 'Whorm Loathsom',
    'Bly', 'Giddean Danu',
  ],
  [
    'Gilgamour', 'Sors Bandeam', 'Ralakili', 'Jeremoch Colton',
    'Whie Malreaux', 'Quay Tolsite', 'Jobal Naberrie', 'Han Solo',
    'Tak', 'Lampay Fay', 'Qi\'ra', 'Karjj',
    'Malé-Dee', 'Tobias Beckett', 'Korso', 'Moteé',
    'Lando Calrissian', 'Sagwa', 'Nee Alavar', 'Val',
    'Margo', 'Po Nudo', 'L3-37', 'Argus Panox',
    'Pooja Naberrie', 'Dryden Vos', 'Benthic', 'Raymus Antilles',
    'Enfys Nest', 'Faddera Rabar', 'Ruwee Naberrie', 'Rio Durant',
    'Gelan Yees', 'Ryoo Naberrie', 'Lady Proxima', 'Hirang Birren',
    'Sheltay Retrac', 'Maul', 'Kane Lankost', 'Sola Naberrie',
    'Rebolt',
  ],
  [
    'Lexi', 'Mon Mothma', 'Jaldine Gerams', 'Moloch',
    'Darth Vader', 'Pterro', 'Ottilie', 'Lyra Erso',
    'Chopper', 'Silvasu Fi', 'Leia Organa', 'Cornelius Evazan',
    'Therm Scissorpunch', 'Davits Draven', 'Rostock', 'Jyn Erso',
    'Raddus', 'Tonc', 'Cassian Andor', 'Antoc Merrick',
    'Edrio Two Tubes', 'K-2SO', 'Jan Dodonna', 'Garven Dreis',
    'Chirrut Îmwe', 'Frobb', 'Corssin', 'Baze Malbus',
    'Gorin', 'Ramda', 'Orson Krennic', 'Bistan',
    'Wona Goban', 'Bodhi Rook', 'Heff Tobber', 'Hurst Romodi',
    'Saw Gerrera', 'Farns Monsbee', 'Jon Vander', 'Galen Erso',
    'Barion Raner',
  ],
  [
    'L-1', 'Vasp Vaspar', 'Chief Jawa', 'Adema',
    'Weeteef Cyubee', 'Davish Krail', 'Casido', 'Luke Skywalker',
    'Dex Tiree', 'Sefla', 'Beru Lars', 'Edmos Khurgee',
    'Moroff', 'Biggs Darklighter', 'Figrin D\'an', 'Nower Jebel',
    'Wedge Antilles', 'Garindan', 'Pao', 'Jek Tono Porkins',
    'John D. Branon', 'Ponda Baba', 'Conan Antonio Motti', 'Kabe',
    'Basteren', 'Cassio Tagge', 'Momaw Nadon', 'Red Twelve',
    'Moradmin Bast', 'Muftak', 'Ruescott Melshi', 'Greedo',
    'R5-D4', 'Tivik', 'Vanden Willard', 'TK-421',
    'Tynnra Pamlo', 'Praji', 'TK-710', 'Vaneé',
    'Arhul Hextrophon',
  ],
  [
    'Wuher', 'Wes Janson', 'Tigran Jamiro', 'Maximilian Veers',
    'Derek "Hobbie" Klivian', 'Toryn Farr', 'Kendal Ozzel', 'Dak Ralter',
    'Ugloste', 'Firmus Piett', '2-1B', 'Venka',
    'Lorth Needa', 'Bewil', 'Willrow Hood', 'Carlist Rieekan',
    'Cabbel', 'Wyron Serper', 'Derlin', 'Cal Alder',
    'Tiaan Jerjerrod', 'Lobot', 'FX-7', 'Gial Ackbar',
    'Bossk', 'Jeroen Webb', 'Crix Madine', 'IG-88',
    'Lennox', 'Nien Nunb', 'Dengar', 'M\'Kae',
    'Arvel Crynyd', 'Zuckuss', 'Nemet', 'Salacious B. Crumb',
    '4-LOM', 'Pharl McQuarrie', 'Oola', 'Zev Senesca',
    'Tamizander Rey',
  ],
  [
    'Sy Snootles', 'Brock Starsher', 'Nanta', 'Max Rebo',
    'Doda Bodonawieedo', 'Nicki', 'Droopy McCool', 'Ephant Mon',
    'Nysad', 'Wicket W. Warrick', 'EV-9D9', 'Pagetti Rook',
    'Chirpa', 'Gailid', 'Pote Snitkin', 'Logray',
    'Greeata Jendowanian', 'Rappertunie', 'Teebo', 'Hermi Odle',
    'Ree-Yees', 'Paploo', 'Joh Yowza', 'Romba',
    '8D8', 'Kithaba', 'Rystáll Sant', 'Ak-rev',
    'Klaatu', 'Saelt-Marae', 'Amanaman', 'Lathe',
    'Sila Kott', 'Barada', 'Lumat', 'Taym Dren-garen',
    'Barquin D\'an', 'Lyn Me', 'Tessek', 'Beedo',
    'Malakili',
  ],
  [
    'Umpass-stay', 'Maz Kanata', 'Korr Sella', 'Vedain',
    'Snoke', 'Teedo', 'Velken Tezeri', 'Armitage Hux',
    'Bala-Tik', 'Vizam', 'Phasma', 'Tasu Leech',
    'Warok', 'Lor San Tekka', 'Razoo Qin-Fee', 'Widdle Warrick',
    'Unkar Plutt', 'Bazine Netal', 'Wol Cabbashite', 'Temmin "Snap" Wexley',
    'Mitaka', 'Yarna d\'al\' Gargan', 'Jessika Pava', 'Datoo',
    'Yotts Orren', 'Ello Asty', 'Kaplan', 'Rey',
    'Statura', 'Thanisson', 'Finn', 'Caluan Ematt',
    'Nastia Unamo', 'Poe Dameron', 'Brance', 'FN-2199',
    'Kylo Ren', 'Kaydel Ko Connix', 'Bobbajo', 'BB-8',
    'Harter Kalonia',
  ],
  [
    'Cypress', 'Prashee', 'Rose Tico', 'Constable Zuvio',
    'Professor Allium', 'Amilyn Holdo', 'Cratinus', 'PZ-4CO',
    'DJ', 'Durteel Haza', 'Quiggold', 'Paige Tico',
    'Pammich Nerro Goode', 'Guich', 'Larma D\'Acy', 'GA-97',
    'Resdox', 'C\'ai Threnalli', 'Goss Toowers', 'Sarco Plank',
    'Tallissan "Tallie" Lintra', 'Grummgar', 'Sidon Ithano', 'Moden Canady',
    'Lanever Villecham', 'Sonsigo', 'Edrison Peavey', 'Bastian',
    'Strono "Cookie" Tuggs', 'Temiri Blagg', 'ME-8D9', 'Tabala Zo',
    'Slowen Lo', 'Munduri', 'Vober Dand', 'Wodibin',
    'Niv Lek', 'Wollivan', 'Neepers Panpick', 'Praster Ommlen',
    'Yolo Ziff',
  ],
  [
    'Lovey', 'Salaka Kuchimba', 'Beaumont Kin', 'Cova Nell',
    'Salty', 'Klaud', 'Derham Boyce', 'Space Gary',
    'Aftab Ackbar', 'Derla Pidys', 'Starck', 'Boolio',
    'Dewn Mison', 'Teene', 'Wrobie Tyce', 'Domaric Quinn',
    'Tubbs', 'Oma Tres', 'Koo Millham', 'D-O',
    'Ap\'lek', 'Nemisis Bond', 'Pryde', 'Cardo',
    'Nix', 'Zorii Bliss', 'Kuruk', 'Pemmin Brunce',
    'Jannah', 'Trudgen', 'Poldin LeHuse', 'Babu Frik',
    'Ushar', 'Reemar Kayvonix', 'Ochi', 'Vicrul',
    'Ronith Blario', 'Dathan', 'Kanan Jarrus', 'Saile Minnau',
    'Miramir',
  ],
]
