/**
 * Regenerate the owl clip modules from the source WebM clips (transparent
 * background, 24fps, 720×544 — the APNGs beside them are deliberately NOT
 * used). The sources live outside the repo; pass their directory:
 *
 *   pnpm tsx scripts/gen-owl-clips.ts "/path/to/OnboardingOwls/transparent"
 *
 * Two files come out:
 * - `src/owl-clips.ts` (host only) — the clip bytes as base64, which the host
 *   face decodes and serves over HTTP.
 * - `src/owl-clip-urls.ts` (both faces) — each step's clip URL. The URL
 *   carries a hash of the clip's bytes, so a changed clip gets a new URL and
 *   the immutable cache never serves a stale one.
 *
 * The client bundle must never import `src/owl-clips.ts`: every window parses
 * its bundle on every boot, and the base64 is ~848 KB.
 */
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

/** Clip id (the wizard step it was drawn for) → source clip file name. */
const CLIPS: Record<string, string> = {
  agents: 'Owl-onboard-agent.webm',
  tools: 'owl-onboard-tools.webm',
  'projects-folder': 'owl-onboard-projects.webm',
  'documentation-folder': 'owl-onboard-documentation.webm',
  finish: 'owl-onboard-complete.webm',
}

/**
 * Steps that reuse another step's clip: the skills folder step (JJ, 15 Sep
 * 2026) has no owl of its own yet and shows the documentation owl.
 */
const SHARED: Record<string, string> = {
  'skills-folder': 'documentation-folder',
}

/** Hex characters of the SHA-256 kept in the URL. */
const HASH_LENGTH = 12

const sourceDir = process.argv[2]
if (sourceDir === undefined || sourceDir === '') {
  console.error('usage: pnpm tsx scripts/gen-owl-clips.ts <OnboardingOwls/transparent dir>')
  process.exit(1)
}

const clips = Object.entries(CLIPS).map(([id, file]) => {
  const bytes = readFileSync(join(sourceDir, file))
  return {
    id,
    base64: bytes.toString('base64'),
    hash: createHash('sha256').update(bytes).digest('hex').slice(0, HASH_LENGTH),
  }
})

const REGENERATE = ` * GENERATED by scripts/gen-owl-clips.ts from sources outside the repo — do
 * not edit by hand; regenerate with:
 *
 *   pnpm tsx scripts/gen-owl-clips.ts "<OnboardingOwls/transparent dir>"`

const bytesOut = fileURLToPath(new URL('../src/owl-clips.ts', import.meta.url))
writeFileSync(bytesOut, `/**
 * The owl clips' bytes (transparent WebM, 24fps, 720×544) as base64. HOST
 * ONLY: the host face decodes and serves them (see ./owl-route.ts); the
 * client bundle must never import this module.
${REGENERATE}
 * @module @idealize/onboarding/owl-clips
 */
import type { OwlClipId } from './owl-clip-urls.ts'

/** Each clip's bytes, base64-encoded. */
export const OWL_CLIP_BASE64: Record<OwlClipId, string> = {
${clips.map(clip => `  '${clip.id}': '${clip.base64}',`).join('\n')}
}
`)

const urlsOut = fileURLToPath(new URL('../src/owl-clip-urls.ts', import.meta.url))
writeFileSync(urlsOut, `/**
 * The owl clips' URLs, shared by both faces: the host serves each clip at its
 * file name under {@link OWL_CLIP_PREFIX} and the browser half points the
 * wizard's \`<video>\` at it. Each file name carries a hash of the clip's
 * bytes, so a changed clip gets a new URL and the immutable cache never serves
 * a stale one. Pure data, so the client program compiles it without the host
 * face's imports.
${REGENERATE}
 * @module @idealize/onboarding/owl-clip-urls
 */
import type { OnboardingStepId } from './step-ids.ts'

/** The route prefix the host serves the clips under. */
export const OWL_CLIP_PREFIX = '/idealize/onboarding/owl'

/** Each clip's served file name: \`<clip id>.<content hash>.webm\`. */
export const OWL_CLIP_FILES = {
${clips.map(clip => `  '${clip.id}': '${clip.id}.${clip.hash}.webm',`).join('\n')}
} as const

/** A clip drawn for the wizard, one per source file. */
export type OwlClipId = keyof typeof OWL_CLIP_FILES

/** The clip each wizard step plays. */
const STEP_CLIPS: Record<OnboardingStepId, OwlClipId> = {
${clips.map(clip => `  '${clip.id}': '${clip.id}',`).join('\n')}
${Object.entries(SHARED).map(([step, from]) => `  '${step}': '${from}',`).join('\n')}
}

/**
 * The clip URL for one wizard step.
 * @param step - the wizard step.
 * @returns the same-origin URL the host serves that step's clip at.
 */
export function owlClipUrl(step: OnboardingStepId): string {
  return \`\${OWL_CLIP_PREFIX}/\${OWL_CLIP_FILES[STEP_CLIPS[step]]}\`
}
`)
console.log(`gen-owl-clips: wrote ${bytesOut} and ${urlsOut}`)
